digitech/apply/api/urls.py
from django.conf.urls import include,url
from .views import ApplicationCreateApiView, ApplicationDetailApiView,\
    ApplicationDeleteApiView, ApplicationUpdateApiView, ApplicationListApiView

from django.contrib import admin


urlpatterns = [
    url(r'^$', ApplicationListApiView.as_view(), name='list'),
    ]
























urlpatterns +=[
    # url(r'^$', apply_power, name='apply'),
    # url(r'^new/$', ApplicationForm.as_view(), name='appli'),
    url(r'^create/$', ApplicationCreateApiView.as_view(), name='create'),
    # url(r'^u/$', ApplicationUpdateView.as_view(), name='update'),
    # url(r'^my-application/$', ApplicationListView.as_view(), name='all-project'),
    url(r'^(?P<pk>\d+)/$', ApplicationDetailApiView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/u/$', ApplicationUpdateApiView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/d/$', ApplicationDeleteApiView.as_view(), name='delete'),
    # url(r'^(?P<pk>\d+)/u/$', application_update, name='application-update'),
    # url(r'^pdf/$', GeneratePdf.as_view()),
    # url(r'^summary/$', views.Summary.as_view(), name='summary'),
    # url(r'^m/$', views.MyApplicationPdf.as_view(), name='pdf'),
]

digitech/apply/urls.py
from django.conf.urls import url

from . views import ApplicationCreateView, ApplicationDetailView, photo_list, \
    ApplicationListView,  ApplicationForm, apply_power, ApplicationUpdateView, application_update, GeneratePdf
from . import views
urlpatterns = [
    url(r'^album$', photo_list, name='album'),
    url(r'^$', apply_power, name='apply'),
    url(r'^new/$', ApplicationForm.as_view(), name='appli'),
    url(r'^nw/$', ApplicationCreateView.as_view(), name='aply'),
    url(r'^u/$', ApplicationUpdateView.as_view(), name='update'),
    url(r'^my-application/$', ApplicationListView.as_view(), name='all-project'),
    url(r'^(?P<pk>\d+)/$', ApplicationDetailView.as_view(), name='application-detail'),
    url(r'^(?P<pk>\d+)/u/$', ApplicationUpdateView.as_view(), name='application-update'),
    # url(r'^(?P<pk>\d+)/u/$', application_update, name='application-update'),
    url(r'^pdf/$', GeneratePdf.as_view()),
    url(r'^summary/$', views.Summary.as_view(), name='summary'),
    url(r'^m/$', views.MyApplicationPdf.as_view(), name='pdf'),
]

digitech/authentication/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
    url(r'^me/$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit/$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)/$', views.ShowProfile.as_view(),
        name='show'),
]

digitech/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from digitech.activities import views as activities_views
from digitech.authentication import views as digitech_auth_views
from digitech.core import views as core_views
from digitech.search import views as search_views
from . import views
from django.contrib import admin
from digitech.authentication import urls as prof_url
from digitech.apply import urls as apply_urls
from digitech.apply.api import urls as apply_api
from digitech.operation import urls as orp_urls
from digitech.apply.views import photo_list

urlpatterns = [
    url(r'', include('user_sessions.urls', 'user_sessions')),
    url(r'^album$', photo_list, name='album'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^gallery/$', views.GalleryPage.as_view(), name='gallery'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    # url(r'^login/$', auth_views.login, {'template_name': 'core/cover.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', digitech_auth_views.signup, name='signup'),
    url(r'^settings/picture/$', core_views.picture, name='picture'),
    url(r'^settings/upload_picture/$', core_views.upload_picture, name='upload_picture'),
    url(r'^settings/save_uploaded_picture/$', core_views.save_uploaded_picture, name='save_uploaded_picture'),
    url(r'^settings/password/$', core_views.password, name='password'),
    url(r'^network/$', core_views.network, name='network'),
    url(r'^feeds/', include('digitech.feeds.urls')),
    url(r'^messages/', include('digitech.messenger.urls')),
    url(r'^notifications/$', activities_views.notifications, name='notifications'),
    url(r'^notifications/last/$', activities_views.last_notifications, name='last_notifications'),
    url(r'^notifications/check/$', activities_views.check_notifications, name='check_notifications'),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^u/(?P<username>[^/]+)/$', core_views.profile, name='profile'),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'^users/', include(prof_url, namespace='profiles')),
    url(r'^op/', include(orp_urls, namespace='operation')),
    url(r'^apply/', include(apply_urls, namespace='apply')),
    url(r'^api/applications/', include(apply_api, namespace='apply-api')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digitech/apply/forms.py
from __future__ import unicode_literals
from django import forms
from django.core.files import File

from django.contrib.auth.forms import AuthenticationForm
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from authtools import forms as authtoolsforms
from django.contrib.auth import forms as authforms
from django.core.urlresolvers import reverse
from digitech.authentication.models import Profile
from django.conf import settings
from .models import Photo
from PIL import Image
from django import forms
from . models import Application



class PowerApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = [
            "my_location",
            # "distance",
            "payment_method",
            'receipt_no',
            'amount'
        ]


class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Photo
        fields = ('file', 'x', 'y', 'width', 'height', )

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.file.path)

        return photo

digitech/apply/api/views.py
from rest_framework.generics import (
        ListAPIView, RetrieveAPIView,
        DestroyAPIView, UpdateAPIView,
        CreateAPIView, RetrieveUpdateAPIView,
    )

from digitech.apply.models import Application
from .serializers import ApplicationSerializer, ApplicationCreateUpdateSerializer,\
    ApplicationDetailSerializer


class ApplicationDetailApiView(RetrieveAPIView):
    queryset = Application.objects.all()
    serializer_class = ApplicationDetailSerializer
    # lookup_field = 'slug'
    # lookup_url_kwarg = 'abc'


class ApplicationUpdateApiView(RetrieveUpdateAPIView):
    queryset = Application.objects.all()
    serializer_class = ApplicationDetailSerializer


class ApplicationDeleteApiView(DestroyAPIView):
    queryset = Application.objects.all()
    serializer_class = ApplicationDetailSerializer


class ApplicationListApiView(ListAPIView):
    queryset = Application.objects.all()
    serializer_class = ApplicationSerializer


class ApplicationCreateApiView(CreateAPIView):
    queryset = Application.objects.all()
    serializer_class = ApplicationCreateUpdateSerializer

    def perfom_create(self, serializer):
        serializer.save(user=self.request.user, amount=5000)

digitech/apply/views.py
from django.views.generic import TemplateView, DetailView, ListView, RedirectView
from . models import Application
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from braces.views import LoginRequiredMixin, SuperuserRequiredMixin
from digitech.operation.mixins import UserAuthorMixin
from . forms import PowerApplicationForm
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.contrib.auth import get_user_model
from .forms import PowerApplicationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.views.generic import View
from digitech.utils import render_to_pdf
from django.template.loader import get_template
from datetime import datetime
from digitech.operation import models
from django_countries import countries

User = get_user_model()


class ApplicationDetailView(LoginRequiredMixin, DetailView):
    # template_name = 'operation/project_detail.html'
    model = Application

    def get_context_data(self, **kwargs):
        context = super(ApplicationDetailView, self).get_context_data(**kwargs)
        context['application_list'] = self.get_queryset()
        return context


class ApplicationListView(SuperuserRequiredMixin, ListView):
    model = Application


class ApplicationCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'apply/apply.html'
    form_class = PowerApplicationForm

    def form_valid(self, form):
        form.instance.author = self.request.user()
        return super(ApplicationCreateView, self).form_invalid(form)


class ApplicationDeleteView(UserAuthorMixin, generic.DeleteView):
    model = Application
    success_url = reverse_lazy('home')


class ApplicationUpdateView(generic.UpdateView):
    template_name = 'apply/update.html'
    model = Application
    form_class = PowerApplicationForm


class ApplicationForm(generic.FormView):
    form_class = PowerApplicationForm
    template_name = 'apply/apply.html'
    success_url = reverse_lazy('home')


@login_required
def apply_power(request):
    form = PowerApplicationForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        # message success
        messages.success(request, "Your application was successfully submited, we will get in touch shortly")
        return redirect(reverse('apply:apply'))
    context = {
        "form": form,
        'title': 'Register a publisher'
    }
    return render(request, "apply/apply.html", context)


def application_update(request, pk=None):
    from django_countries import countries
    countries = list(countries)[:10]
    instance = get_object_or_404(Application, pk=pk)
    form = PowerApplicationForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Your application details were successfully updated", extra_tags='html_safe')
        return redirect(reverse('apply:apply'))

    context = {
        "instance": instance,
        "form": form,
        'countries': countries,
    }
    return render(request, "apply/update.html", context)


class GeneratePdf(View):
    def get(self, request, *args, **kwargs):
        template = get_template('apply/pdf/invoice.html')
        context = {
            'today': datetime.now(),
            'amount': 39.99,
            'customer_name': 'Cooper Mann',
            'invoice_id': 1233434,
        }
        pdf = render_to_pdf('apply/pdf/invoice.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Invoice_%s.pdf" %("123")
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" % (filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")


class MyApplicationPdf(View):
    def get(self, request, *args, **kwargs):
        template = get_template('apply/pdf/application.html')
        user = request.user
        context = {
            'today': datetime.now(),
            'amount': 39.99,
            'customer_name': 'Cooper Mann',
            'invoice_id': 1233434,
            'user': user
        }
        pdf = render_to_pdf('apply/pdf/application.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Invoice_%s.pdf" % user
            content = "inline; filename='%s'" % filename
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" % filename
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")


class Summary(View):
    def get(self, request, *args, **kwargs):
        application_list = Application.objects.all()
        user_list = User.objects.all()
        transformer_list = models.Transformer.objects.all()
        machinery_list = models.Machinery.objects.all()
        employee_list = models.Employee.objects.all()
        project_list = models.Project.objects.all()
        template = get_template('apply/pdf/summary.html')
        user = request.user
        context = {
            'today': datetime.now(),
            'application_list': application_list,
            'user_list': user_list,
            'transformer_list': transformer_list,
            'machinery_list': machinery_list,
            'employee_list': employee_list,
            'project_list': project_list,
            'user': user,
        }
        pdf = render_to_pdf('apply/pdf/summary.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            from django.utils import timezone
            now = datetime.now()
            filename = "summary-%s.pdf" % now
            content = "inline; filename='%s'" % filename
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" % filename
            response['Content-Disposition'] = content
            return response
        return HttpResponse(""
                            "Not found")


from django.shortcuts import render, redirect
from .models import Photo
from .forms import PhotoForm


def photo_list(request):
    photos = Photo.objects.all()
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('photo_list')
    else:
        form = PhotoForm()
    return render(request, 'album/photo_list.html', {'form': form, 'photos': photos})

digitech/apply/templates/apply/application_detail.html
{% extends 'base.html' %}
{% block main %}
    <div class="container">

      <div class="starter-template">
        <h1>Application Complete</h1>
        <p class="lead">Thank You for your application. We will be reaching you shortly.<br>
            At Digitech Power ltd. we aim at providing the best for every.</p>
      </div>
    </div><!-- /.container -->
    {% endblock main %}

digitech/apply/templates/apply/applied.html
{% load crispy_forms_tags %}

{% load staticfiles i18n %}

<div class="row">
    <h3 class="has-error">You have Already Apllied for Power</h3>
    <p>Your current details are shown below: <br>
    </p>
    <p>If you have errors you can
        <a class="btn btn-default" href="{{ user.application.get_absolute_url }}u">Update Application</a>
        <a class="btn btn-warning" href="{% url 'profiles:edit_self' %}">Update Profile</a>
    </p>
    <div class="col-sm-8">
        <div class="panel panel-default"  style="font-size: 1.1em;">
        <div class="panel-heading panel-primary">
            <strong><u>{{ user|upper }}</u></strong>
            <img src="{{ user.profile.get_picture }}" alt="" height="30" class="img-circle pull-right">
            <br>
            <small>Aplied on <i>{{ user.application.update }}</i></small>
            <br>
            <hr>
        <div class="row">
        <div class="col-xs-5">
            <strong>
                First Name:
            </strong>
        </div>
        <div class="col-xs-7">
            {% if user.first_name %}
                {{ user.first_name }}
            {% else %}
                <i class="fa fa-warning danger" style="color: red;"></i> First name is required
            {% endif %}
        </div>
        </div>
        <div class="row">
        <div class="col-xs-5">
            <strong>
                Last Name:
            </strong>
        </div>
        <div class="col-xs-7">
            {% if user.last_name %}
                {{ user.last_name }}
            {% else %}
                <i class="fa fa-warning danger" style="color: red;"></i> Last name is required
            {% endif %}
        </div>
        </div>
        <div class="row">
        <div class="col-xs-5">
            <strong>
                Email:
            </strong>
        </div>
        <div class="col-xs-7">
            {% if user.email %}
                {{ user.email }}
            {% else %}
                <i class="fa fa-warning danger" style="color: red;"></i> Email is required
            {% endif %}
        </div>
        </div>
        <div class="row">
        <div class="col-xs-5">
            <strong>
                Phone:
            </strong>
        </div>
        <div class="col-xs-7">
            {% if user.profile.phone %}
                +254{{ user.profile.phone }}
            {% else %}
                <i class="fa fa-warning danger" style="color: red;"></i> Phone number is required
            {% endif %}
        </div>
        </div>
        <div class="row">
        <div class="col-xs-5">
            <strong>
                Residence:
            </strong>
        </div>
        <div class="col-xs-7">
            {% if user.profile.residence %}
                {{ user.profile.residence }}
            {% else %}
                <i class="fa fa-warning danger" style="color: red;"></i> Your Residence is required
            {% endif %}
        </div>
        </div>
        <div class="row">
        <div class="col-xs-5">
            <strong>
                ID No:
            </strong>
        </div>
        <div class="col-xs-7">
            {% if user.profile.id_no %}
                {{ user.profile.id_no }}
            {% else %}
                <i class="fa fa-warning danger" style="color: red;"></i> ID is required
            {% endif %}
        </div>
        </div>
{#        <div class="row">#}
{#        <div class="col-xs-5">#}
{#            <strong>#}
{#                Nearest Transformer:#}
{#            </strong>#}
{#        </div>#}
{#        <div class="col-xs-7">#}
{#            {% if user.application.transformer %}#}
{#                {{ user.application.transformer }}#}
{#            {% else %}#}
{#                <i class="fa fa-warning danger" style="color: red;"></i> A transformer is required#}
{#            {% endif %}#}
{#        </div>#}
{#        </div>#}
        <div class="row">
        <div class="col-xs-5">
            <strong>
                Payment Method:
            </strong>
        </div>
        <div class="col-xs-7">
            {% if user.application.payment_method %}
                {{ user.application.payment_method }}
            {% else %}
                <i class="fa fa-warning danger" style="color: red;"></i> Payment Method is required
            {% endif %}
        </div>
        </div>
        <div class="row">
        <div class="col-xs-5">
            <strong>
                Receipt No:
            </strong>
        </div>
        <div class="col-xs-7">
            {% if user.application.receipt_no %}
                {{ user.application.receipt_no }}
            {% else %}
                <i class="fa fa-warning danger" style="color: red;"></i> Receipt No. is required
            {% endif %}
        </div>
        </div>
{#        <div class="row">#}
{#        <div class="col-xs-5">#}
{#            <strong>#}
{#                Distance from Transformer:#}
{#            </strong>#}
{#        </div>#}
{#        <div class="col-xs-7">#}
{#            {% if user.application.distance %}#}
{#                {{ user.application.distance }}m#}
{#            {% else %}#}
{#                <i class="fa fa-warning danger" style="color: red;"></i> Distance is required#}
{#            {% endif %}#}
{#        </div>#}
{#        </div>#}

        </div>
        <a href="{% url 'apply:pdf' %}">
           View Application <i class="fa fa-eye fa-2x"></i>
        </a>
        <p><a href=" {% url 'apply:pdf' %}?download={{ user.id }}">
           Print The application <i class="fa fa-print fa-2x"></i>
        </a></p>
</div>
</div>
</div>

digitech/apply/templates/apply/apply.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load staticfiles i18n %}

{% block head %}
{#  <link href="{% static 'css/signup.css' %}" rel="stylesheet">#}
{% endblock head %}

{% block main %}

{% if not user.first_name or not user.last_name or not user.email or not user.profile.phone or not user.profile.id_no %}
    <div class="container">
      <div class="starter-template">
        <h1>Sorry for This!!</h1>
        <p class="lead">Some of your details are mising. It seems You have not yet completed your profile.<br>
            Please update your profile before you proceed.
            <a class="btn btn-xs btn-default" href="{% url 'profiles:edit_self' %}">Update Profile</a>
        </p>
      </div>
    </div><!-- /.container -->
{% else %}

{% if user.application %}
{% include 'apply/applied.html' %}
{% else %}
    <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <h1 class="logo"><a href="{% url 'home' %}">Digitech Power Application</a></h1>
    <div class="signup">
    <h2>Make an application</h2>
    <form action="{% url 'apply:apply' %}" method="post" role="form">
      {% csrf_token %}
    {{ form.media }}
      {{ form|crispy }}
      <button type="submit" class="btn btn-lg btn-primary btn-block">{% trans 'Send Application' %}</button>
        <br><br>
    </form>
  </div>
    </div>
    {% endif %}
    {% endif %}
{% endblock main %}

digitech/apply/templates/apply/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load staticfiles i18n %}

{% block head %}
{#  <link href="{% static 'css/signup.css' %}" rel="stylesheet">#}
{% endblock head %}

{% block main %}
{#    <a href="{% url 'apply:application-update' %}">mw hwwhjdfjhdjhdfjh</a>#}
      <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <h1 class="logo"><a href="{% url 'home' %}">Digitech Power Application</a></h1>
    <div class="signup">
    <h2>Make an application</h2>
    <form action="" method="post" role="form">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-lg btn-primary btn-block">{% trans 'Send Application' %}</button>
        <br><br>
    </form>
        {% load countries %}
    {% get_country 'KE' as country %}
    {{ country.name }}
  </div>
    </div>
{% endblock main %}