digitech/apply/api/urls.py
from django.conf.urls import include,url
from .views import ApplicationCreateApiView, ApplicationDetailApiView,\
    ApplicationDeleteApiView, ApplicationUpdateApiView, ApplicationListApiView

from django.contrib import admin


urlpatterns = [
    url(r'^$', ApplicationListApiView.as_view(), name='list'),
    ]
























urlpatterns +=[
    # url(r'^$', apply_power, name='apply'),
    # url(r'^new/$', ApplicationForm.as_view(), name='appli'),
    url(r'^create/$', ApplicationCreateApiView.as_view(), name='create'),
    # url(r'^u/$', ApplicationUpdateView.as_view(), name='update'),
    # url(r'^my-application/$', ApplicationListView.as_view(), name='all-project'),
    url(r'^(?P<pk>\d+)/$', ApplicationDetailApiView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/u/$', ApplicationUpdateApiView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/d/$', ApplicationDeleteApiView.as_view(), name='delete'),
    # url(r'^(?P<pk>\d+)/u/$', application_update, name='application-update'),
    # url(r'^pdf/$', GeneratePdf.as_view()),
    # url(r'^summary/$', views.Summary.as_view(), name='summary'),
    # url(r'^m/$', views.MyApplicationPdf.as_view(), name='pdf'),
]

digitech/apply/urls.py
from django.conf.urls import url

from . views import ApplicationCreateView, ApplicationDetailView, photo_list, \
    ApplicationListView,  ApplicationForm, apply_power, ApplicationUpdateView, application_update, GeneratePdf
from . import views
urlpatterns = [
    url(r'^album$', photo_list, name='album'),
    url(r'^$', apply_power, name='apply'),
    url(r'^new/$', ApplicationForm.as_view(), name='appli'),
    url(r'^nw/$', ApplicationCreateView.as_view(), name='aply'),
    url(r'^u/$', ApplicationUpdateView.as_view(), name='update'),
    url(r'^my-application/$', ApplicationListView.as_view(), name='all-project'),
    url(r'^(?P<pk>\d+)/$', ApplicationDetailView.as_view(), name='application-detail'),
    url(r'^(?P<pk>\d+)/u/$', ApplicationUpdateView.as_view(), name='application-update'),
    # url(r'^(?P<pk>\d+)/u/$', application_update, name='application-update'),
    url(r'^pdf/$', GeneratePdf.as_view()),
    url(r'^summary/$', views.Summary.as_view(), name='summary'),
    url(r'^m/$', views.MyApplicationPdf.as_view(), name='pdf'),
]

digitech/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from digitech.activities import views as activities_views
from digitech.authentication import views as digitech_auth_views
from digitech.core import views as core_views
from digitech.search import views as search_views
from . import views
from django.contrib import admin
from digitech.authentication import urls as prof_url
from digitech.apply import urls as apply_urls
from digitech.apply.api import urls as apply_api
from digitech.operation import urls as orp_urls
from digitech.apply.views import photo_list

urlpatterns = [
    url(r'', include('user_sessions.urls', 'user_sessions')),
    url(r'^album$', photo_list, name='album'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^gallery/$', views.GalleryPage.as_view(), name='gallery'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    # url(r'^login/$', auth_views.login, {'template_name': 'core/cover.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', digitech_auth_views.signup, name='signup'),
    url(r'^settings/picture/$', core_views.picture, name='picture'),
    url(r'^settings/upload_picture/$', core_views.upload_picture, name='upload_picture'),
    url(r'^settings/save_uploaded_picture/$', core_views.save_uploaded_picture, name='save_uploaded_picture'),
    url(r'^settings/password/$', core_views.password, name='password'),
    url(r'^network/$', core_views.network, name='network'),
    url(r'^feeds/', include('digitech.feeds.urls')),
    url(r'^messages/', include('digitech.messenger.urls')),
    url(r'^notifications/$', activities_views.notifications, name='notifications'),
    url(r'^notifications/last/$', activities_views.last_notifications, name='last_notifications'),
    url(r'^notifications/check/$', activities_views.check_notifications, name='check_notifications'),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^u/(?P<username>[^/]+)/$', core_views.profile, name='profile'),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'^users/', include(prof_url, namespace='profiles')),
    url(r'^op/', include(orp_urls, namespace='operation')),
    url(r'^apply/', include(apply_urls, namespace='apply')),
    url(r'^api/applications/', include(apply_api, namespace='apply-api')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digitech/apply/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib import admin
from digitech.operation.models import Transformer, Location, Employee, Machinery
from django.utils import timezone
from django.utils.text import slugify
from django.db.models.signals import pre_save
from geoposition.fields import GeopositionField


class ApplicationManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(ApplicationManager, self).filter(installed=False)


class Application(models.Model):
    transformer = models.ForeignKey(Transformer, related_name='transformer', null=True, blank=True)
    my_location = GeopositionField('Where you want power to be installed', null=True, blank=True)
    distance = models.IntegerField('Distance from Transformer', default=0)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='application', null=True, blank=True)
    receipt_no = models.CharField('Receipt No:', max_length=30, null=True, blank=True)
    M_PESA = 'MPESA'
    KCB = 'KCB'
    LATER = 'NOT YET PAID'
    CO_OP = 'CO-OP'
    EQUITY = 'EQUITY'
    PAYMENT_METHODS = (
        (LATER, 'I will pay later'),
        (M_PESA, 'M-PESA paybill no. 34589'),
        (KCB, 'KCB Eldoret branch Account No. 12345670089'),
        (CO_OP, 'CO-OPERATIVE bank Account No 09872346875'),
        (EQUITY, 'EQUITY bank Account No 83294847829'),
        )
    payment_method = models.CharField('Your convenient payment method', null=True, blank=True,
                                      max_length=12, choices=PAYMENT_METHODS)
    amount = models.IntegerField('Amount Payed', default=0)
    installation = models.DateField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)
    message = models.TextField(null=True, blank=True)
    employee = models.ManyToManyField(Employee, related_name='employee')
    installed = models.BooleanField(default=False)


    def get_absolute_url(self):
        return reverse("apply:application-detail", kwargs={"pk": self.id})

    class Meta:
        verbose_name = 'Power Application'
        verbose_name_plural = 'Power Applications'

    def __str__(self):
        return '{0} at {1}'.format(self.user, self.my_location)



class Photo(models.Model):
    file = models.ImageField()
    description = models.CharField(max_length=255, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'

digitech/operation/models.py
from django.db import models
from geoposition.fields import GeopositionField
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib import admin
from django.db.models.signals import pre_save
from django.utils.text import slugify


class Location(models.Model):
    name = models.CharField(max_length=50, unique=True)
    position = GeopositionField()
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("academics:timetable-item", kwargs={"slug": self.slug})
admin.site.register(Location)


class Organization(models.Model):
    name = models.CharField(max_length=255)
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    location = models.ForeignKey(Location, null=True, blank=True)
    description = models.TextField(default='More info ...')

    def __str__(self):
        return self.name
admin.site.register(Organization)


class PowerLine(models.Model):
    name = models.CharField(max_length=255)
    source = models.ForeignKey(Location,)
    voltage = models.IntegerField(default=0)
    description = models.TextField(default='More info ...')

    def __str__(self):
        return self.name
admin.site.register(PowerLine)


class Transformer(models.Model):
    id = models.CharField(max_length=30, unique=True, primary_key=True)
    location = models.ForeignKey(Location, null=True, blank=True, related_name='location')
    power_line = models.OneToOneField(PowerLine, null=True, blank=True)
    input = models.IntegerField(null=True, blank=True)
    output = models.IntegerField(null=True, blank=True)
    date = models.DateTimeField('Installation date ', null=True, blank=True)

    def __str__(self):
        return 'T{0}'.format(self.id)

admin.site.register(Transformer)


class Machinery(models.Model):
    name = models.CharField(max_length=50)
    no = models.CharField(max_length=30, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='machine_img',
                              null=True,
                              blank=True,
                              width_field="width_field",
                              height_field="height_field")
    width_field = models.IntegerField(default=0)
    height_field = models.IntegerField(default=0)

    def __str__(self):
        return self.name

admin.site.register(Machinery)


class Rank(models.Model):
    title = models.CharField(null=True, blank=True, max_length=50)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title
admin.site.register(Rank)


class Employee(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    id = models.CharField(max_length=15, primary_key=True, unique=True)
    rank = models.ForeignKey(Rank, null=True, blank=True)

    def __str__(self):
        return self.id

admin.site.register(Employee)


class Project(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    from_date = models.DateField()
    to_date = models.DateField()
    image = models.ImageField(upload_to='project_img',
                              null=True,
                              blank=True,
                              width_field="width_field",
                              height_field="height_field")
    width_field = models.IntegerField(default=0)
    height_field = models.IntegerField(default=0)
    slug = models.SlugField(unique=True, blank=False, null=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("operation:project-detail", kwargs={"pk": self.id})
    # def get_absolute_url(self):
    #     return reverse("operation:project", kwargs={"slug": self.slug})


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Project.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_project_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_project_receiver, sender=Project)
admin.site.register(Project)

digitech/apply/forms.py
from __future__ import unicode_literals
from django import forms
from django.core.files import File

from django.contrib.auth.forms import AuthenticationForm
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from authtools import forms as authtoolsforms
from django.contrib.auth import forms as authforms
from django.core.urlresolvers import reverse
from digitech.authentication.models import Profile
from django.conf import settings
from .models import Photo
from PIL import Image
from django import forms
from . models import Application



class PowerApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = [
            "my_location",
            # "distance",
            "payment_method",
            'receipt_no',
            'amount'
        ]


class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Photo
        fields = ('file', 'x', 'y', 'width', 'height', )

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.file.path)

        return photo

digitech/apply/api/views.py
from rest_framework.generics import (
        ListAPIView, RetrieveAPIView,
        DestroyAPIView, UpdateAPIView,
        CreateAPIView, RetrieveUpdateAPIView,
    )

from digitech.apply.models import Application
from .serializers import ApplicationSerializer, ApplicationCreateUpdateSerializer,\
    ApplicationDetailSerializer


class ApplicationDetailApiView(RetrieveAPIView):
    queryset = Application.objects.all()
    serializer_class = ApplicationDetailSerializer
    # lookup_field = 'slug'
    # lookup_url_kwarg = 'abc'


class ApplicationUpdateApiView(RetrieveUpdateAPIView):
    queryset = Application.objects.all()
    serializer_class = ApplicationDetailSerializer


class ApplicationDeleteApiView(DestroyAPIView):
    queryset = Application.objects.all()
    serializer_class = ApplicationDetailSerializer


class ApplicationListApiView(ListAPIView):
    queryset = Application.objects.all()
    serializer_class = ApplicationSerializer


class ApplicationCreateApiView(CreateAPIView):
    queryset = Application.objects.all()
    serializer_class = ApplicationCreateUpdateSerializer

    def perfom_create(self, serializer):
        serializer.save(user=self.request.user, amount=5000)

digitech/apply/templates/apply/pdf/application.html
{% load static %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
 <html>
     <head>
         <title>{{ user }}</title>
         <style type="text/css">
             body {
                 font-weight: 200;
                 font-size: 14px;
             }
             .header {
                 font-size: 20px;
                 font-weight: 100;
                 text-align: center;
                 color: #007cae;
             }
             .title {
                 font-size: 22px;
                 font-weight: 100;
                /* text-align: right;*/
                padding: 10px 20px 0px 20px;
             }
             .title span {
                 color: #007cae;
             }
             .details {
                 padding: 10px 30px 0px 50px;
                 text-align: left !important;
                 /*margin-left: 40%;*/
             }
             .hrItem {
                 border: none;
                 height: 1px;
                 /* Set the hr color */
                 color: #333; /* old IE */
                 background-color: #fff; /* Modern Browsers */
             }
             hr{margin-left: 100px;}
{#            table {#}
{#                width:100%;#}
{#            }#}
            table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
            }
            th, td {
                padding: 5px;
                text-align: left;
            }
         </style>


     </head>
     <body>
         <div class='container'>
             <div class='header'>
                 <p class='title'>{% include '_brandname.html' %} POWER APPLICATION </p>
             </div>
             <div class="details">
                 <img src="{% static 'logos/img/mu.png' %}" alt="">
                 {% include '_address.html' %}
                 Ref: MPL-0{{ user.id }}-{{ user.application.payment_method }}-0{{ user.application.id }}
             <hr/>
            <table class="details">
                <th>Detail</th><th colspan="2">Description</th>
                <tr><td>Applicant Name</td><td colspan="2">{{ user.first_name }} {{ user.last_name }}</td></tr>
                <tr><td>Email</td><td colspan="2">{{ user.email }}</td></tr>
                <tr><td>Naitional ID NO.</td><td colspan="2">{{ user.profile.id_no }}</td></tr>
                <tr><td>Residence</td><td colspan="2">{{ user.profile.residence }}</td></tr>
                <tr><td>Phone</td><td colspan="2">{{ user.profile.phone }}</td></tr>
{#                <tr><td>Transformer</td><td colspan="2">{{ user.application.transformer }}</td></tr>#}
{#                <tr><td>Distance from transformer</td><td colspan="2">{{ user.application.distance }}m</td></tr>#}
                <tr><td>Date of Application</td><td colspan="2">{{ user.application.update }}</td></tr>
                <tr><td>Payement Method</td><td colspan="2">{{ user.application.payment_method }}</td></tr>
                <tr><td>Receipt No:</td><td colspan="2">{{ user.application.receipt_no }}</td></tr>
                <tr><td>Amount Paid</td><td colspan="2">Ksh. {{ user.application.amount }}.00</td></tr>
            </table>
                    <p>This is an unofficial Document and is subject to sole ownership of &copy;{% include '_brandname.html' %} The official receipt will be provided
                    after the installation is complete.</p>
                 <p>We acknowledge your acceptance of our terms and conditions</p>
                 <p>Name: ..............................Sign: ................... Date:.............</p>
                 </div>

             </div>
         </div>
     </body>
 </html>

digitech/apply/templates/apply/pdf/invoice.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
 <html>
     <head>
         <title>New Title </title>
         <style type="text/css">
             body {
                 font-weight: 200;
                 font-size: 14px;
             }
             .header {
                 font-size: 20px;
                 font-weight: 100;
                 text-align: center;
                 color: #007cae;
             }
             .title {
                 font-size: 22px;
                 font-weight: 100;
                /* text-align: right;*/
                padding: 10px 20px 0px 20px;
             }
             .title span {
                 color: #007cae;
             }
             .details {
                 padding: 10px 20px 0px 20px;
                 text-align: left !important;
                 /*margin-left: 40%;*/
             }
             .hrItem {
                 border: none;
                 height: 1px;
                 /* Set the hr color */
                 color: #333; /* old IE */
                 background-color: #fff; /* Modern Browsers */
             }
         </style>
     </head>
     <body>
         <div class='wrapper'>
             <div class='header'>
                 <p class='title'>Invoice # {{ invoice_id }} </p>
             </div>
         <div>
         <div class='details'>
             Bill to: {{ customer_name }} <br/>
             Amount: {{ amount }} <br/>
             Date: {{ today }}
             <hr class='hrItem' />
         </div>
         </div>
         </div>
     </body>
 </html>

digitech/apply/templates/apply/pdf/summary.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
 <html>
     <head>
         <title>New Title </title>
         <style type="text/css">
             body {
                 font-weight: 200;
                 font-size: 14px;
             }
             .header {
                 font-size: 20px;
                 font-weight: 100;
                 text-align: center;
                 color: #007cae;
             }
             .title {
                 font-size: 22px;
                 font-weight: 100;
                /* text-align: right;*/
                padding: 10px 20px 0px 20px;
             }
             .title span {
                 color: #007cae;
             }
             .details {
                 padding: 10px 20px 0px 50px;
                 text-align: left !important;
                 /*margin-left: 40%;*/
             }
             .hrItem {
                 border: none;
                 height: 1px;
                 /* Set the hr color */
                 color: #333; /* old IE */
                 background-color: #fff; /* Modern Browsers */
             }
             table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
            }
            th, td {
                padding: 3px;
                text-align: left;
            }
         </style>
     </head>
     <body>
         <div class='wrapper'>
             <div class='header'>
                 <p class='title'>{% include '_brandname.html' %} Organization Summary</p>
             </div>
         <div class="details">{% include '_address.html' %}
            {{ today }}
             <br><br>
                      <table>
                 <caption style="margin-left: 300px;"><centre>Users</centre></caption>
                 <tr><th>No:</th><th colspan="2">Name</th><th colspan="2">Email</th></tr>
                {% for user in user_list %}
                  <tr><td>{{ forloop.counter }}:</td>
                      <td colspan="2">{{ user.first_name|capfirst }} {{ user.last_name|capfirst }} [{{ user.username }}]</td>
                    <td colspan="2">{{ user.email }}</td>
                  </tr>
                {% endfor %}
                </table>
             <br>
             <table>
                 <caption style="margin-left: 300px;"><centre>Power Applications</centre></caption>
                 <tr><th>No:</th><th colspan="2">Tranformer</th><th colspan="2">Applied by</th><th colspan="2">Date</th></tr>
                {% for application in application_list %}
                  <tr><td>{{ forloop.counter }}:</td> <td colspan="2">{{ application.transformer }}</td>
                    <td colspan="2">{{ application.user.username }}</td><td colspan="2">{{ application.update }}</td>
                  </tr>
                {% endfor %}
                </table>
             <br>
                      <table>
                 <caption style="margin-left: 300px;"><centre>Transformer Installations</centre></caption>
                 <tr><th>No:</th><th colspan="2">Tranformer</th><th colspan="2">Location</th><th colspan="2">Date</th></tr>
                {% for transformer in transformer_list %}
                  <tr><td>{{ forloop.counter }}:</td> <td colspan="2">{{ transformer }}</td>
                    <td colspan="2">{{ transformer.location }}</td><td colspan="2">{{ transformer.date }}</td>
                  </tr>
                {% endfor %}
                </table>
                      <br>
             <table>
                 <caption style="margin-left: 300px;"><centre>Machines</centre></caption>
                 <tr><th>No:</th><th colspan="2">Name</th><th colspan="2">No</th>
                {% for machine in machinery_list %}
                  <tr><td>{{ forloop.counter }}:</td> <td colspan="2">{{ machine.name }}</td>
                    <td colspan="2">{{ machine.no }}</td>
                  </tr>
                {% endfor %}
                </table>
             <br>
                      <br>
             <table>
                 <caption style="margin-left: 300px;"><centre>Employees</centre></caption>
                 <tr><th>No:</th><th colspan="2">Name </th><th colspan="2">Employee No</th><th colspan="2">Rank</th></tr>
                {% for employee in employee_list %}
                  <tr><td>{{ forloop.counter }}:</td> <td colspan="2">{{ employee.user.first_name }} {{ employee.user.last_name }}</td>
                    <td colspan="2">{{ employee.id }}</td><td colspan="2">{{ employee.rank }}</td>
                  </tr>
                {% endfor %}
                </table>
             <br>             <br>
             <table>
                 <caption style="margin-left: 300px;"><centre>Projects</centre></caption>
                 <tr><th>No:</th><th colspan="2">Name</th><th colspan="2">Starting Date</th><th colspan="2">Ending Date</th></tr>
                {% for project in project_list %}
                  <tr><td>{{ forloop.counter }}:</td> <td colspan="2">{{ project.name }}</td>
                    <td colspan="2">{{ project.from_date }}</td><td colspan="2">{{ project.to_date }}</td>
                  </tr>
                {% endfor %}
                </table>
             <br>             <br>


         </div>
         </div>
     </body>
 </html>