digitech/authentication/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
    url(r'^me/$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit/$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)/$', views.ShowProfile.as_view(),
        name='show'),
]

digitech/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from digitech.activities import views as activities_views
from digitech.authentication import views as digitech_auth_views
from digitech.core import views as core_views
from digitech.search import views as search_views
from . import views
from django.contrib import admin
from digitech.authentication import urls as prof_url
from digitech.apply import urls as apply_urls
from digitech.apply.api import urls as apply_api
from digitech.operation import urls as orp_urls
from digitech.apply.views import photo_list

urlpatterns = [
    url(r'', include('user_sessions.urls', 'user_sessions')),
    url(r'^album$', photo_list, name='album'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^gallery/$', views.GalleryPage.as_view(), name='gallery'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    # url(r'^login/$', auth_views.login, {'template_name': 'core/cover.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', digitech_auth_views.signup, name='signup'),
    url(r'^settings/picture/$', core_views.picture, name='picture'),
    url(r'^settings/upload_picture/$', core_views.upload_picture, name='upload_picture'),
    url(r'^settings/save_uploaded_picture/$', core_views.save_uploaded_picture, name='save_uploaded_picture'),
    url(r'^settings/password/$', core_views.password, name='password'),
    url(r'^network/$', core_views.network, name='network'),
    url(r'^feeds/', include('digitech.feeds.urls')),
    url(r'^messages/', include('digitech.messenger.urls')),
    url(r'^notifications/$', activities_views.notifications, name='notifications'),
    url(r'^notifications/last/$', activities_views.last_notifications, name='last_notifications'),
    url(r'^notifications/check/$', activities_views.check_notifications, name='check_notifications'),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^u/(?P<username>[^/]+)/$', core_views.profile, name='profile'),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'^users/', include(prof_url, namespace='profiles')),
    url(r'^op/', include(orp_urls, namespace='operation')),
    url(r'^apply/', include(apply_urls, namespace='apply')),
    url(r'^api/applications/', include(apply_api, namespace='apply-api')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digitech/core/forms.py
from django import forms
from django.contrib.auth.models import User


class ChangePasswordForm(forms.ModelForm):
    id = forms.CharField(widget=forms.HiddenInput())
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Old password",
        required=True)

    new_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="New password",
        required=True)
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Confirm new password",
        required=True)

    class Meta:
        model = User
        fields = ['id', 'old_password', 'new_password', 'confirm_password']

    def clean(self):
        super(ChangePasswordForm, self).clean()
        old_password = self.cleaned_data.get('old_password')
        new_password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')
        id = self.cleaned_data.get('id')
        user = User.objects.get(pk=id)
        if not user.check_password(old_password):
            self._errors['old_password'] = self.error_class([
                'Old password don\'t match'])
        if new_password and new_password != confirm_password:
            self._errors['new_password'] = self.error_class([
                'Passwords don\'t match'])
        return self.cleaned_data

digitech/core/views.py
import os
from django.conf import settings as django_settings
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, redirect, render

from digitech.core.forms import ChangePasswordForm
from digitech.feeds.models import Feed
from digitech.feeds.views import FEEDS_NUM_PAGES
from PIL import Image


@login_required
def network(request):
    users_list = User.objects.filter(is_active=True).order_by('username')
    paginator = Paginator(users_list, 100)
    page = request.GET.get('page')
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    return render(request, 'core/network.html', {'users': users})


@login_required
def profile(request, username):
    page_user = get_object_or_404(User, username=username)
    all_feeds = Feed.get_feeds().filter(user=page_user)
    paginator = Paginator(all_feeds, FEEDS_NUM_PAGES)
    feeds = paginator.page(1)
    from_feed = -1
    if feeds:
        from_feed = feeds[0].id
    return render(request, 'core/profile.html', {
        'page_user': page_user,
        'feeds': feeds,
        'from_feed': from_feed,
        'page': 1
        })


@login_required
def picture(request):
    uploaded_picture = False
    try:
        if request.GET.get('upload_picture') == 'uploaded':
            uploaded_picture = True

    except Exception:
        pass

    return render(request, 'core/picture.html',
                  {'uploaded_picture': uploaded_picture})


@login_required
def password(request):
    user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get('new_password')
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 'Your password was successfully changed.')
            return redirect('password')

    else:
        form = ChangePasswordForm(instance=user)

    return render(request, 'core/password.html', {'form': form})


@login_required
def upload_picture(request):
    try:
        profile_pictures = django_settings.MEDIA_ROOT + '/profile_pictures/'
        if not os.path.exists(profile_pictures):
            os.makedirs(profile_pictures)
        f = request.FILES['picture']
        filename = profile_pictures + request.user.username + '_tmp.jpg'
        with open(filename, 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
        im = Image.open(filename)
        width, height = im.size
        if width > 350:
            new_width = 350
            new_height = (height * 350) / width
            new_size = new_width, new_height
            im.thumbnail(new_size, Image.ANTIALIAS)
            im.save(filename)

        return redirect('/settings/picture/?upload_picture=uploaded')

    except Exception as e:
        print(e)
        return redirect('/settings/picture/')


@login_required
def save_uploaded_picture(request):
    try:
        x = int(request.POST.get('x'))
        y = int(request.POST.get('y'))
        w = int(request.POST.get('w'))
        h = int(request.POST.get('h'))
        tmp_filename = django_settings.MEDIA_ROOT + '/profile_pictures/' +\
            request.user.username + '_tmp.jpg'
        filename = django_settings.MEDIA_ROOT + '/profile_pictures/' +\
            request.user.username + '.jpg'
        im = Image.open(tmp_filename)
        cropped_im = im.crop((x, y, w+x, h+y))
        cropped_im.thumbnail((200, 200), Image.ANTIALIAS)
        cropped_im.save(filename)
        os.remove(tmp_filename)

    except Exception:
        pass

    return redirect('/settings/picture/')

digitech/core/templates/core/cover.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block head %}
  <link href="{% static 'css/signup.css' %}" rel="stylesheet">
{% endblock head %}
{#    {% block styles %}#}
{#    {% endblock styles %}#}

{% block body %}
    <div class="container">
  <div class="col-sm-6 col-sm-offset-3">
  <div class="col-md-10 col-md-offset-1">
      <h1 class="logo" style="margin-top: 25px;!important;">Digitech</h1>
    {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ error }}
        </div>
      {% endfor %}
    {% endif %}
    <div class="signup">
      <h2>{% trans 'Log in' %}</h2>
      <form method="post" action="{% url 'login' %}" role="form">
        {% csrf_token %}
        <div class="form-group{% if form.username.errors %} has-error{% endif %}">
          <label for="username">{% trans 'Username' %}</label>
          <input type="text" class="form-control" id="username" name="username">
          {% for error in form.username.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
        <div class="form-group{% if form.password.errors %} has-error{% endif %}">
          <label for="password">{% trans 'Password' %}</label>
          <input type="password" class="form-control" id="password" name="password">
          {% for error in form.password.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
            <a href="{% url 'profiles:password-reset' %}">Forgot password</a>
        <br>
        <label>Remember Me</label>
            <input type="checkbox">
            <br>
        <div class="form-group">
          <button type="submit" class="btn btn-success btn-block btn-lg">{% trans 'Log in' %}</button> <br>
        </div>
      </form>
    Do not have an account
          <a href="{% url 'signup' %}">Signup</a> <br>
    </div>
  </div>
  </div>
  </div>

{% endblock body %}

digitech/core/templates/core/network.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block title %}{% trans 'Network' %}{% endblock %}
{% block head %}
<link href="{% static 'css/network.css' %}" rel="stylesheet">
{% endblock head %}
{% block main %}
  <div class="page-header">
    <h1>Network</h1>
  </div>
  <div class="users">
      {% for user in users %}
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading">
             {{ forloop.counter }} <img src="{{ user.profile.get_picture }}" style="width:20px">
              <a href="{% url 'profile' user.username %}">{{ user.profile.get_screen_name }}</a>
            </div>
            <div class="panel-body">
              {% if user.profile.job_title %}
                <p><strong>{% trans 'Job Title' %}:</strong> {{ user.profile.job_title }}</p>
              {% endif %}
              <p><strong>{% trans 'Username' %}: </strong> {{ user.username }}</p>
              {% if user.profile.location %}
                <p><strong>{% trans 'Location' %}:</strong> {{ user.profile.location }}</p>
              {% endif %}
              {% if user.profile.url %}
                <p><strong>{% trans 'Url' %}:</strong> {{ user.profile.get_url }}</p>
              {% endif %}
            </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
      {% endfor %}
    </div>

    <div class="row">
      <div class="col-md-12">
        {% include 'paginator.html' with paginator=users %}
      </div>
    </div>
{% endblock main %}

digitech/core/templates/core/partial_settings_menu.html
{% load i18n %}
<div class="list-group">
  <a href="{% url 'profiles:edit_self' %}" class="list-group-item{% if active == 'profile' %} active{% endif %}">{% trans 'Profile' %}</a>
  <a href="{% url 'picture' %}" class="list-group-item{% if active == 'picture' %} active{% endif %}">{% trans 'Picture' %}</a>
  <a href="{% url 'password' %}" class="list-group-item{% if active == 'password' %} active{% endif %}">{% trans 'Password' %}</a>
</div>

digitech/core/templates/core/password.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Account Settings' %}{% endblock %}

{% block messages %}
{% endblock messages %}
{% block main %}
  <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-sm-3">
      {% include 'core/partial_settings_menu.html' with active='password' %}
    </div>
    <div class="col-sm-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Change Password' %}</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'password' %}">
        {% csrf_token %}
        {{ form.id }}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-3 control-label">{{ field.label }}</label>
            <div class="col-sm-9">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock main %}

digitech/core/templates/core/picture.html
{% extends 'base.html' %}

{% load i18n static %}

{% block title %}{% trans 'Account Settings' %}{% endblock %}

{% block head %}
  <link href="{% static 'css/jquery.Jcrop.min.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery.Jcrop.min.js' %}"></script>
  <script src="{% static 'js/picture.js' %}"></script>
{% endblock head %}

{% block main %}
  <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-sm-3">
      {% include 'core/partial_settings_menu.html' with active='picture' %}
    </div>
    <div class="col-sm-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Change Picture' %}</h3>
      <img src="{{ user.profile.get_picture }}" style="width: 150px; border-radius: 5px; margin-bottom: 1em;">
      <form enctype="multipart/form-data" method="post" action="{% url 'upload_picture' %}" id="picture-upload-form">
        {% csrf_token %}
        <input type="file" name="picture" style="display: none">
        <button type="button" class="btn btn-default" id="btn-upload-picture">{% trans 'Upload new picture' %}</button>
      </form>

      {% if uploaded_picture %}
        <form method="post" action="{% url 'save_uploaded_picture' %}">
          {% csrf_token %}
          <div class="modal fade" id="modal-upload-picture">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title">{% trans 'Crop Picture' %}</h4>
                </div>
                <div class="modal-body">
                  <div class="selected-picture">
                    <p>{% trans 'Crop the profile picture and then click on the' %} <strong>{% trans 'Save Picture' %}</strong> {% trans 'button' %}</p>
                    <img src="{% get_media_prefix %}profile_pictures/{{ user.username }}_tmp.jpg?_={% now 'U' %}" id="crop-picture">
                    <input type="hidden" id="x" name="x" />
                    <input type="hidden" id="y" name="y" />
                    <input type="hidden" id="w" name="w" />
                    <input type="hidden" id="h" name="h" />
                  </div>
                  <script type="text/javascript">
                    $(function () {
                      $("#modal-upload-picture").modal();
                      window.history.pushState("", "", "/settings/picture/");
                    });
                  </script>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
                  <button type="submit" class="btn btn-primary">{% trans 'Save changes' %}</button>
                </div>
              </div>
            </div>
          </div>
        </form>
      {% endif %}
    </div>
  </div>
{% endblock main %}

digitech/core/templates/core/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}{{ page_user.profile.get_screen_name }}{% endblock %}

{% block head %}
  <link href="{% static 'css/profile.css' %}" rel="stylesheet">
  <link href="{% static 'css/feeds.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery.bullseye-1.0-min.js' %}"></script>
  <script src="{% static 'js/feeds.js' %}"></script>
{% endblock head %}

{% block main %}
  <div class="page-header">
    <h1>{{ page_user.profile.get_screen_name }} {% if page_user.get_full_name %}<small>({{ page_user.username }})</small>{% endif %}</h1>
  </div>
  <div class="profile">
    <div class="row">
      <div class="col-md-3 user-profile">
        <img src="{{ page_user.profile.get_picture }}" class="picture">
        <ul>
          {% if page_user.profile.job_title %}
          <li><span class="glyphicon glyphicon-briefcase"></span> {{ page_user.profile.job_title }}</li>
          {% endif %}
          {% if page_user.profile.location %}
          <li><span class="glyphicon glyphicon-map-marker"></span> {{ page_user.profile.location }}</li>
          {% endif %}
          {% if page_user.profile.url %}
          <li><span class="glyphicon glyphicon-globe"></span> <a href="{{ page_user.profile.get_url }}" target="_blank">{{ page_user.profile.get_url }}</a></li>
          {% endif %}
        </ul>
      </div>
      <div class="col-md-9">
        <h4>{% trans 'Last Feeds by' %} {{ page_user.profile.get_screen_name }}</h4>
        <div class="stream-update">
          <a href="#"><span class="new-posts"></span> new posts</a>
        </div>
        <ul class="stream">
          {% for feed in feeds %}
            {% include 'feeds/partial_feed.html' with feed=feed %}
          {% endfor %}
        </ul>
        <div class="load">
          <img src="{% static 'img/loading.gif' %}">
        </div>
        <form method="get" action="{% url 'load' %}" id="load_feed" autocomplete="off">
          <input type="hidden" name="feed_source" id="feed_source" value="{{ page_user.pk }}">
          <input type="hidden" name="from_feed" value="{{ from_feed }}">
          <input type="hidden" name="page" value="{{ page }}">
        </form>
      </div>
    </div>
  </div>
{% endblock main %}